In [2]:
import numpy as np

In [20]:
X = np.array([[7, 4, 3], [4, 1, 8], [6, 3, 5], [8, 6, 1], [8, 5, 7], [7, 2, 9], [5, 3, 3], [9, 5, 8], [7, 4, 5], [8, 2, 2]])
eigen_vec = np.array([[-0.70, 0.71, 0.08], [0.70, 0.66, 0.27], [-0.14, -0.25, 0.96]])
eigen_val = np.array([0.75, 3.68, 8.27])

X_cov = np.cov(X.T)
X_mean = X.mean(axis=0)
X_minus_mean = X - X_mean

In [23]:
X

array([[7, 4, 3],
       [4, 1, 8],
       [6, 3, 5],
       [8, 6, 1],
       [8, 5, 7],
       [7, 2, 9],
       [5, 3, 3],
       [9, 5, 8],
       [7, 4, 5],
       [8, 2, 2]])

In [22]:
X_minus_mean

array([[ 0.1,  0.5, -2.1],
       [-2.9, -2.5,  2.9],
       [-0.9, -0.5, -0.1],
       [ 1.1,  2.5, -4.1],
       [ 1.1,  1.5,  1.9],
       [ 0.1, -1.5,  3.9],
       [-1.9, -0.5, -2.1],
       [ 2.1,  1.5,  2.9],
       [ 0.1,  0.5, -0.1],
       [ 1.1, -1.5, -3.1]])

In [24]:
X.shape, X_cov.shape

((10, 3), (3, 3))

In [37]:
Z = X_minus_mean.dot(eigen_vec.T)
Z, Z.shape

(array([[ 0.117, -0.167, -2.155],
        [ 0.487, -2.897,  3.815],
        [ 0.267, -0.987,  0.155],
        [ 0.677,  1.313, -4.715],
        [ 0.447,  2.273,  1.295],
        [-0.823,  0.133,  4.105],
        [ 0.807, -2.227, -1.625],
        [-0.173,  3.243,  2.115],
        [ 0.277,  0.373, -0.235],
        [-2.083, -1.057, -2.755]]),
 (10, 3))

### Reconstructing using all eigen vectors

In [30]:
Z.dot(eigen_vec) + X_mean

array([[7.0029 , 4.0116 , 2.99547],
       [3.9971 , 0.98   , 8.01917],
       [6.0005 , 2.9994 , 5.00367],
       [8.0053 , 6.026  , 0.98227],
       [7.9969 , 4.9938 , 6.99267],
       [6.9945 , 1.9772 , 9.01087],
       [5.0037 , 3.0094 , 3.00327],
       [8.9951 , 4.9888 , 7.99217],
       [7.0001 , 4.0016 , 4.99727],
       [8.0039 , 2.0122 , 2.00317]])

In [31]:
X_minus_mean.shape, eigen_vec.shape

((10, 3), (3, 3))

### Reconstructing using n eigen vectors

In [52]:
n = 2

Z_n = X_minus_mean[:, :n].dot(eigen_vec[:n, :])
Z_n.shape

(10, 3)

In [53]:
Z_n.dot(eigen_vec) + X_mean

array([[6.96468, 3.92771, 5.36795],
       [4.23468, 1.47761, 3.25025],
       [6.05468, 3.11101, 4.66205],
       [7.80888, 5.60951, 6.56725],
       [7.87468, 4.74441, 6.07385],
       [7.09628, 2.19751, 4.38115],
       [5.07888, 3.15941, 4.44955],
       [8.85048, 4.69601, 6.28635],
       [6.96468, 3.92771, 5.36795],
       [8.07208, 2.14911, 4.59365]])